# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zvan-de- <zvan-de-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/14 13:45:36 by zvandeven         #+#    #+#              #
#    Updated: 2023/04/05 18:05:52 by zvan-de-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#------------------------------------------------------------------------------#
#                                VARIABLES                                     #
#------------------------------------------------------------------------------#
NAME 		= libft.a
CC			= gcc
RM			= rm -f
CFLAGS		= -g -Wall -Wextra -Werror
BINDIR		= bin/
OBJS 		= $(addprefix $(BINDIR), $(SRCS:.c=.o))
SRCS		=  ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c \
ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c \
ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c\
ft_atoi.c ft_strdup.c ft_substr.c ft_calloc.c\
ft_substr.c ft_strjoin.c ft_strtrim.c ft_itoa.c\
ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c\
ft_putendl_fd.c ft_putnbr_fd.c ft_split.c\
ft_lstnew.c ft_lstadd_front.c ft_lstsize.c\
ft_lstlast.c ft_lstdelone.c ft_lstadd_back.c\
ft_lstiter.c ft_lstmap.c ft_lstclear.c ft_putnbr_base.c\
ft_printf/ft_printf.c\
ft_printf/ft_printf_utils.c\
ft_printf/ft_putnbr_pf.c\
ft_printf/ft_putunsign.c\
ft_printf/ft_putnbr_base_pf.c\
ft_printf/ft_printadr.c\

#colors
G = \033[0;32m
RT = \033[0m

#------------------------------------------------------------------------------#
#                                 RULES                                        #
#------------------------------------------------------------------------------#

all: $(NAME)

$(NAME): $(BINDIR) $(OBJS)
	ar rc $(NAME) $(OBJS)

$(BINDIR)%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(BINDIR) :
	mkdir $(BINDIR)
	mkdir $(BINDIR)ft_printf

clean:
	$(RM) $(OBJS)
	$(RM) -r $(BINDIR) 

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY:		all bonus clean fclean re